version: "3.9"
services:
  pusher:
    build:
      context: push/
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_SERVER: "redis"
  puller:
    build:
      context: pull/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - pusher
    environment:
      REDIS_SERVER: "redis"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
      
